### ISSUE TITLE
Original file modified

### ISSUE THREAD

**Issue by cmoulliard** [bucharest-gold/litoria#17]
When this function is called to find/replace a string within the file `where test/temp/simple/html-cfg.yaml`

https://github.com/bucharest-gold/litoria/blob/master/test/common.js#L51-L56

```
var searchReplaceStringInFile = function (filePath, stringToSearch, stringToBeReplaced) {
  let rex = new RegExp(stringToSearch, 'g');
  let file = fs.readFileSync(filePath, 'utf8').toString();
  let result = file.replace(rex, stringToBeReplaced);
  fs.writeFileSync(filePath, result);
};
```

then the original file (= file which has been copied to test/temp/simple folder) is also overwritten with the modifications !

```
git diff templates/config/html-cfg.yaml
diff --git a/templates/config/html-cfg.yaml b/templates/config/html-cfg.yaml
index 60ae2c9..b2afdeb 100644
--- a/templates/config/html-cfg.yaml
+++ b/templates/config/html-cfg.yaml
@@ -1,4 +1,4 @@
-source: "./source" # directory path or name of the file to be processed: ./source/simple.adoc
+source: "./source/simple.adoc" # directory path or name of the file to be processed: ./source/simple.adoc
 destination: "./generated"

 file_to_inline: "./generated/output.html"
@@ -6,8 +6,8 @@ file_inlined: "./generated/output-inlined.html"

 attributes:
   showtitle: ''
-  stylesheet: 'foundation.css'
-  stylesdir: 'css'
+  
+  
   nofooter: 'yes'
   icons: 'font'
   # linkcss: 'true' # Don't use this option if you want to embed the CSS
```

**Comment by helio-frota** [comment]
I suspect this is due the hard link from : 
https://github.com/bucharest-gold/litoria/blob/master/lib/litoria.js#L594


https://nodejs.org/api/fs.html#fs_fs_linksync_existingpath_newpath
http://man7.org/linux/man-pages/man2/link.2.html

> link() creates a new link (also known as a hard link) to an existing file.

If yes we need to write a new copyFile approach.
